alias sve="source venv/bin/activate"
alias youtube-dl-audio= "youtube-dl --extract-audio --audio-format mp3"
alias edit_zshrc="nano ~/.zshrc && source ~/.zshrc"
alias eik="code ~/Documents/Everything-I-Know"
export repos="~/Documents/repos"

# Find and set branch name var if in git repository.
function git_branch_name()
{
  branch=$(git symbolic-ref HEAD 2> /dev/null | awk 'BEGIN{FS="/"} {print $NF}')
  if [[ $branch == "" ]];
  then
    :
  else
    echo '- ('$branch')'
  fi
}

# Enable substitution in the prompt.
setopt prompt_subst

# Config for prompt. PS1 synonym.
prompt='%2/ $(git_branch_name) > '

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/ezracitron/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/ezracitron/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/ezracitron/opt/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/ezracitron/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

